### ISSUE TITLE
obtain file location of overlays and arm9 sections!

### ISSUE THREAD

**Issue by EliCrystal2001** [RoadrunnerWMC/ndspy#4]
right now im currently just doing 
`def find_in_rom(code_section):
	return rom_bytes.index(code_section)`

feel like it could be better .. idk

**Comment by RoadrunnerWMC** [comment]
ndspy fully unpacks the ROM (or code file) when you load it and repacks it when you save it, so file offsets for things in a loaded ROM aren't static. Calculating the offset of something in the ROM data would require packing the ROM and noting the offset it was saved at -- and it'd only be valid for that particular packing, since any subsequent changes to the ROM could shift everything again.

In general, everything in ndspy works this way. There's no way to obtain offsets for things in a file, because the library fully unpacks and repacks every supported file. Making an exception for ROMs and code files would be rather strange and inconsistent.

From a design standpoint, it's also not clear if things would keep track of the offsets they were loaded from (which could become invalid later, and also wouldn't easily be applied to things like `bytes`) or if it should tell you the offsets it saves things to (which would only be valid for that one packing, and would also affect performance and increase RAM usage in all cases unless I made duplicate code paths for it). Overall, it'd be a fair bit of added complexity for an uncommon use case.

I think your current solution is best. To make it robust in case there are identical code sections or overlays, you could save the ROM twice, with the first byte of the section set to different values, then check for where the changed byte is. Or alternatively, you could parse the ROM or code data yourself a bit, just enough to locate the offsets you're interested in; that would let you also correctly handle empty overlays / sections.

Sorry to turn down your idea; by design, ndspy sacrifices some uncommon use cases like this for convenience on more common ones. I've actually had to do workarounds like this myself in the past, even though I wrote the library... it just is what it is. Best of luck!
